name: Build Docker image

on:
  push:
    branches: [ main, unit_test ]
  workflow_dispatch:

jobs:
  test:
    if: github.ref == 'refs/heads/unit_test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Install dependencies
        run: Rscript -e 'install.packages(c("testthat"))'

      - name: Run tests
        run: testthat::test_dir("tests/testthat")

  docker:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare lowercase vars
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/akwamo-webservice-next-dashboard:latest
          progress: plain  # Enable debug output
